name: SonarCloud analysis
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '/' '_')
          echo "Repository Name: $REPO_NAME"
          # Use the $REPO_NAME in the subsequent steps
